//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int PropertyManagerID { get; set; }
        public int TenantID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public int AddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
