//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public Nullable<int> PropertyManagerID { get; set; }
        public Nullable<int> PropertyOwnerID { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> EventTypeID { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
