//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public int SenderID { get; set; }
        public int ReceiverID { get; set; }
        public string Subject { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public int MessageStatusID { get; set; }
    
        public virtual MessageStatus MessageStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
